config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :overview
  resources :targets

  root to: 'overview#index'
end

app/models/actual.rb
class Actual < ActiveRecord::Base
  belongs_to :targets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/target.rb
class Target < ActiveRecord::Base
  has_many :actuals
  has_many :target_days
  accepts_nested_attributes_for :actuals
  accepts_nested_attributes_for :target_days


  def create_target_days(date)
    (date.beginning_of_month..date.end_of_month).each do |day|
      TargetDay.find_or_create_by(:day => day, :target_id => self.id)
    end
  end
end

app/models/target_day.rb
class TargetDay < ActiveRecord::Base
  belongs_to :target_days

  # For simple calendar
  def start_time
    self.day
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login


  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end

  def is_admin?
    current_user && current_user.admin
  end

  def must_be_admin
    unless is_admin?
      redirect_to login_path, alert: "Administrators only"
    end
  end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  def index
    @time_period = (params[:time_period] && (VALID_TIME_PERIODS.include? params[:time_period])) || "week"
    @targets = Target.all
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  def index
  end

  def update
    # Update for targets / actuals and targets days
    @target = Target.find(params[:id])
    @target.update_attributes(target_params)

    if params['target']['target_days_attributes']
      # target days updated
      redirect_to overview_index_path, :notice => "#{@target.name} targets updated!"
    else
      redirect_to overview_index_path, :notice => "updated #{@target.name}"
    end
  end


  def edit
    # Edit for targets / actuals and targets days
    date = params[:start_date] ? params[:start_date].to_date : Time.now.to_date

    @target      = Target.find(params[:id])
    @target.create_target_days(date)
  end



  private
  def target_params
    params.require(:target).permit(:name, :actuals_attributes => [:amount], :target_days_attributes => [:id, :day, :amount])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action      :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]
  before_action      :must_be_admin, only: [:index, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, notice: 'User was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/target_helper.rb
module TargetHelper
  def get_sum_of_period(ar, time_period)
    raise("please use one of the following time periods: #{VALID_TIME_PERIODS.join(', ')}") unless VALID_TIME_PERIODS.include? time_period

    # target uses a day, actuals use updated_at
    date_column = ar.try(:first).try(:day) ? :day : :updated_at
    range = (Date.current.send("beginning_of_#{time_period}")+1.minute)..Date.current.send("end_of_#{time_period}")

    ar.send("group_by_#{time_period}", *[date_column, {range: range, last: 0}]).sum(:amount).try(:first).try(:last)
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
  def get_sum_of_period(ar, time_period)
    raise("please use one of the following time periods: #{VALID_TIME_PERIODS.join(', ')}") unless VALID_TIME_PERIODS.include? time_period

    # targets uses a day, actuals use updated_at
    date_column = ar.try(:first).try(:day) ? :day : :updated_at
    range = (Date.current.send("beginning_of_#{time_period}")+1.second)..Date.current.send("end_of_#{time_period}")+1.day-1.second

    ar.send("group_by_#{time_period}", *[date_column, {range: range, last: 0}]).sum(:amount).try(:first).try(:last)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="callout <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
          <%= content_tag :div, msg %>
          <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    <% end %>
<% end %>

app/views/layouts/_top.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">my targets</li>
      <li><%= link_to "overview", overview_index_path %></li>
      <li><%= link_to "add new target", new_target_path %></li>
      <li><%= link_to "edit targets", new_target_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <% if current_user %>
        <%= link_to "Edit Profile", edit_user_path(current_user.id) %> |
        <%= link_to "Logout", :logout, method: :post %>
    <% else %>
        <%= link_to "Register", new_user_path %> |
        <%= link_to "Login", :login %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "My Targets" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/top' %>
    <%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

app/views/overview/_target.html.erb
<% sum_of_targets = get_sum_of_period(target.target_days, @time_period) %>
<% sum_of_actuals = get_sum_of_period(target.actuals,     @time_period) %>
<% perct_reached  = sum_of_targets > 0 ? (sum_of_actuals*100 / sum_of_targets).round(2) : 0 %>

<div class="small-12 medium-6 large-3 columns">
  <div class="row align-center">
    <div class="small-11 columns align-self-middle" style="background-color:#e0e0e0;">
      <div class="target_box">

        <div class="space"></div>
        <div class="row"><strong><%= target.name.try(:downcase) %>:</strong></div>
        <div class="row"><%= sum_of_targets %> <%= target.measurement_unit %> per <%= @time_period %>.</div>
        <div class="row"><%= perct_reached.to_i %> %</div>


        <div class="space"></div>
        <div class="space"></div>


        <div class="row">
          <progress value="<%= [perct_reached.to_i,100].min %>" max="100"></progress>
        </div>

        <div class="row">
          <%= form_for(target, :html => {:'data-abide' => '' }) do |target_form| %>
              <div class="input-group">
                <%= target_form.fields_for :actuals, target.actuals.build do |actual_field| %>
                    <%= actual_field.text_field :amount, :label => false, :type => "number", :class => "input-group-field", :required => ''%>
                <% end %>
                <div class="input-group-button">
                  <%= target_form.submit :class => "button", :value => "add update", data: { :disable_with => false} %>
                </div>
              </div>
          <% end %>
        </div>

        <div class="row">
          <div class="small-12 columns">
            <div class="float-right">
              <p id="open_panel_<%= target.id %>" class="float-left">
                <a data-toggle="panel_<%= target.id %>" class="right">
                  <%= with_details ? "close" : "details" %>
                </a>
              </p>

            <%= link_to "/edit", edit_target_path(target) %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/overview/_target_detailed.html.erb
<div class="small-12 medium-6 large-9 columns">
  <h4>Hello!</h4>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dicta?</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dicta?</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dicta?</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dicta?</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dicta?</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dicta?</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dicta?</p>
  </div>
</div>

app/views/overview/_toggle.js.erb
  var item = document.getElementById("open_panel_<%= target.id %>");


  //        item.addEventListener("mouseover", mouse_in, false);
  //       item.addEventListener("mouseout", mouse_out, false);

  item.onclick = mouse_in();

  function mouse_in()
  {
      console.log("#target_group_<%= target_group_no %>");
      $("#target_group_<%= target_group_no %>").foundation('toggle');
      console.log("sdf");
      //         $("#panel_<%= target.id %>").foundation('toggle');
      }

  function mouse_out()
  {
      $("#target_group_<%= target_group_no %>").foundation('toggle');
      $("#panel_<%= target.id %>").foundation('toggle');
      }

app/views/overview/index.html.erb
<%# We want 4 targets on one row %>
<div class="row">&nbsp;</div>

<% @targets.find_in_batches(:batch_size => 4).with_index do |target_group, target_group_no| %>
    <div class="row">&nbsp;</div>
    <div class="row" id="target_group_<%= target_group_no %>" data-toggler data-animate="fade-in fade-out">
      <% target_group.each do |target| %>
          <%= render partial: "target", locals: {target: target, with_details: false} %>
      <% end %>
    </div>

    <div class="row">&nbsp;</div>

    <% target_group.each do |target| %>
        <div class="row" id="panel_<%= target.id %>" data-toggler data-animate="fade-in fade-out" style="display:none">
          <%= render partial: "target", locals: {target: target, with_details: true} %>
          <%= render partial: "target_detailed" %>
        </div>
    <% end %>
<% end %>

app/views/overview/update.js.erb
console.log("something updated");

app/views/targets/edit.html.erb
<div class="row">&nbsp;</div>
<div class="row"><h4><%= @target.name.try(:downcase) %></h4></div>
<div class="row">
  <%= form_for(@target, remote: false) do |target_form| %>
      <%= month_calendar events: @target.target_days do |date, target_days| %>
          <div class="float-right"><small><%= date.strftime("%d") %></small></div>
              <%= target_form.fields_for :target_days, target_days do |target_day_f| %>
                  <%= target_day_f.text_field :amount, :type => "number", :class => "input-group-field" %>
              <% end %>
      <% end %>

      <div class="row">
        <div class="small-1 columns">
          <input type="text" name="total" id="total" style="background-color: #dddddd;" />
        </div>
        <div class="small-11 columns">
          <%= target_form.submit :class => "button float-right", :value => "add update" %>
        </div>
      </div>
  <% end %>
</div>



<script>
  function update_total() {
    var inputs = $(".input-group-field")
    var sum = 0;

    for (var i=0; i < inputs.length; i++){
      sum += parseFloat(inputs[i].value) || 0;
      console.log(sum);
    }
    $("#total").val(sum);
  }


  $("form.edit_target").on("change" , function(e){
    update_total();
  });

  $(document).ready(function(){ update_total();})
</script>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br />
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Login", :class => "button" %>
    </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>